spring:
  application:
    name: automessage
  profiles:
    active: local
    include: api
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/sms;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    username: root
#    password: ${DB_PASSWORD}
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://${SERVER_URL}/khanMessage

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #        use_sql_comments: true
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
server:
  port: 8002

