spring:
  application:
    name: automessage
  profiles:
    active: local
    include: api
  datasource:
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${SERVER_URL}/khanMessage
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:tcp://localhost/~/sms;MODE=MYSQL

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        use_sql_comments: true
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}

  h2:
    console:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

  endpoints:
    web:
      exposure:
        include: ${INCLUDE}
      base-path: ${BASE_PATH}

logging:
  level:
    hello.controller: debug

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8002
  forward-headers-strategy: native
  address: 127.0.0.1

