spring:
  application:
    name: automessage

  profiles:
    active: local
    include: api
  datasource:
    url: jdbc:h2:tcp://localhost/~/sms
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        #        use_sql_comments: true
        default_batch_fetch_size: 10

  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace