spring:
  application:
    name: automessage
  profiles:
    active: test
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace

